### ISSUE TITLE
(Urgent) build broken due to workflow setup

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsml-ruby#14]
@suleman-uzair the build is currently broken due to the last step in the workflow. Can you please help fix it? Thanks!

**Comment by suleman-uzair** [comment]
@ronaldtse 
The build was broken due to [bad credentials error](https://github.com/unitsml/unitsml-ruby/actions/runs/5888633783/job/15970449791).
As you can see in the screenshot below, the token [UNITSML_CI_PAT_TOKEN](https://github.com/unitsml/unitsml-ruby/blob/main/.github/workflows/rake.yml#L15) is missing.
![Screenshot from 2023-08-17 14-16-27](https://github.com/unitsml/unitsml-ruby/assets/96812483/8d845b87-d0cb-47bb-8909-6196ff8d24b0)
![Screenshot from 2023-08-17 14-17-38](https://github.com/unitsml/unitsml-ruby/assets/96812483/1b877cd9-3876-49e3-bd4a-c9db66647f9e)

**Comment by ronaldtse** [comment]
Why does testing require any token?

**Comment by ronaldtse** [comment]
The token has always been present though.

<img width="826" alt="Screenshot 2023-08-17 at 6 49 37 PM" src="https://github.com/unitsml/unitsml-ruby/assets/11865/fe76862d-ee9b-4ba8-8a7e-75c2b3100f53">

**Comment by ronaldtse** [comment]
@CAMOBAP can you please help here?

1. Why do we need a CI user token for just testing?
2. The token exists, why is it failing?

**Comment by suleman-uzair** [comment]
I am not completely sure but I don’t think this token is needed here.
@CAMOBAP can you confirm whether this token is required in this repository ?
https://github.com/unitsml/unitsml-ruby/blob/main/.github/workflows/rake.yml#L15
I will just test by removing the token and dispatching the workflow, and there is a good chance that it will function as expected.

**Comment by CAMOBAP** [comment]
> Why do we need a CI user token for just testing?

We don't need it, it came because we used it in metanorma repo because they can trigger other repositories

> The token exists, why is it failing?

It may not have required permissions to send repository_dispatch events

Fixed in https://github.com/unitsml/unitsml-ruby/pull/15
